[package]
name = "ft-vox-prototype-0-map-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ft-vox-prototype-0-noise = { version = "0.1.0", path = "../noise" }
ft-vox-prototype-0-map-types = { version = "0.1.0", path = "../map_types" }
