[workspace]
resolver = "2"
members = [
    "core",
    "exe",
    "main",
    "map_core",
    "map_types",
    "module_loader",
    "noise",
    "noise_test",
    "terrain_worker_native",
    "terrain_worker_web",
    "util_lru_cache_arc",
    "util_lru_cache_rc",
]
default-members = ["exe"]
