[workspace]
resolver = "2"
members = [
    "core",
    "main",
    "map_core",
    "map_types",
    "noise",
    "noise_test",
    "lib/rust/tmap_wrapper",
    "lib/rust/mod_loader",
    "lib/rust/library_wrapper",
]
default-members = ["main"]
