[workspace]
resolver = "2"
members = [
    "core",
    "client",
    "map_core",
    "map_types",
    "noise",
    "noise_test",
    "server",
    "messages",
]
default-members = ["client", "server"]
