[package]
name = "ft-vox-prototype-0-exe"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
ft-vox-prototype-0-main = { path = "../main" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ft-vox-prototype-0-terrain-worker-native = { path = "../terrain_worker_native" }
